Repository kcp-dev/embeddedetcd, pull requests merged in 2025-04, with the labels that each got.

#1 Sync go mod deps with kcp-dev/kcp
  go.mod
  go.sum
Labels: dco-signoff: yes, size/L, lgtm

#3 Add owners file
  OWNERS
Labels: dco-signoff: yes, size/XS, do-not-merge/hold

#2 Remove kcp-dev/sdk dependency
  go.mod
  go.sum
Labels: dco-signoff: yes, size/L, approved
